# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'decent_exposure', '3.0.0'
gem 'jwt'
gem 'puma', '~> 4.1'
gem 'rabl'
gem 'rack-cors'
gem 'rails', '~> 6.0.3'
gem 'rubocop'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
